-- ///////////////////
-- // ACCOUNT
-- ///////////////////
CREATE TABLE IF NOT EXISTS auth.account
(
    id       UUID PRIMARY KEY     DEFAULT GEN_RANDOM_UUID(),
    name     CITEXT      NOT NULL,
    email    CITEXT      NOT NULL,
    disabled BOOLEAN     NOT NULL DEFAULT FALSE,
    created  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT check__name_length CHECK (CHAR_LENGTH(name) BETWEEN 3 AND 32),
    CONSTRAINT check__email_length CHECK (CHAR_LENGTH(email) BETWEEN 6 AND 254)
);
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_trigger
                       WHERE tgname = 'account_update_current_timestamp'
                         AND tgrelid = 'auth.account'::regclass) THEN
            CREATE TRIGGER account_update_current_timestamp
                BEFORE UPDATE
                ON auth.account
                FOR EACH ROW
            EXECUTE FUNCTION auth.update_current_timestamp();
        END IF;
    END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS account__name_unique ON auth.account (name);
CREATE UNIQUE INDEX IF NOT EXISTS account__email_unique ON auth.account (email);

-- ///////////////////
-- // PROVIDERS
-- ///////////////////
CREATE TABLE IF NOT EXISTS auth.provider
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     CITEXT      NOT NULL,
    disabled BOOLEAN     NOT NULL DEFAULT FALSE,
    created  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check__name_length CHECK (CHAR_LENGTH(name) BETWEEN 3 AND 255)
);
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_trigger
                       WHERE tgname = 'provider_update_current_timestamp'
                         AND tgrelid = 'auth.provider'::regclass) THEN
            CREATE TRIGGER provider_update_current_timestamp
                BEFORE UPDATE
                ON auth.provider
                FOR EACH ROW
            EXECUTE FUNCTION auth.update_current_timestamp();
        END IF;
    END
$$;


CREATE UNIQUE INDEX IF NOT EXISTS provider__name_unique ON auth.provider (name);

-- ///////////////////
-- // CREDENTIALS
-- ///////////////////
CREATE TABLE IF NOT EXISTS auth.account_credentials
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  UUID        NOT NULL REFERENCES auth.account (id) ON DELETE CASCADE,
    provider_id BIGINT      NOT NULL REFERENCES auth.provider (id) ON DELETE RESTRICT,

    secret      TEXT        NOT NULL,
    secret_type TEXT        NOT NULL DEFAULT 'password', -- sha256, pem, opaque

    verified    BOOLEAN     NOT NULL DEFAULT FALSE,
    verified_at TIMESTAMPTZ,

    disabled    BOOLEAN     NOT NULL DEFAULT FALSE,
    disabled_at TIMESTAMPTZ,

    created     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (account_id, provider_id),
    CONSTRAINT check__verified_requires_timestamp
        CHECK ((verified = FALSE AND verified_at IS NULL) OR (verified = TRUE AND verified_at IS NOT NULL)),

    CONSTRAINT check__disabled_requires_timestamp
        CHECK ((disabled = FALSE AND disabled_at IS NULL) OR (disabled = TRUE AND disabled_at IS NOT NULL))
);
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_trigger
                       WHERE tgname = 'account_credentials_update_current_timestamp'
                         AND tgrelid = 'auth.account_credentials'::regclass) THEN
            CREATE TRIGGER account_credentials_update_current_timestamp
                BEFORE UPDATE
                ON auth.account_credentials
                FOR EACH ROW
            EXECUTE FUNCTION auth.update_current_timestamp();
        END IF;
    END
$$;

